### ISSUE TITLE
cannot download 'http://www.opengis.net/ont/gml'!

### ISSUE THREAD

**Issue by ChengWang2018** [lu-w/criticality-recognition#1]
Hello Lukas,

When I run the code, i get the following error. Could you please explain why? Thank you!

cannot download 'http://www.opengis.net/ont/gml'!

**Comment by lu-w** [comment]
Hi Cheng,

it seems like your machine is not able to fetch a copy of the ontology located at http://www.opengis.net/ont/gml. This can have many reasons, e.g. due to restrictions of the (corporate) network you are in. 

What happens if you open the link in your browser? Does it show you an RDF file for the GML? 

If not, you can try to fetch a copy elsewhere and store it locally on your disk. You would then need to edit the `catalog-v001.xml` in `auto/ontology` by adding the following lines:

```xml 
<uri id="User Entered Import Resolution" name="http://www.opengis.net/ont/gml" uri="location_of_your_copy.rdf"/>
```

**Comment by ChengWang2018** [comment]
Hello Lukas,

Thanks a lot. I have add the line as you suggested. That is really helpful. I fetched a copy through another internet. Thanks!

Just for confirmation. after adding the lines, I have to comment/delete these two lines in geosparql.rdf
    <owl:Ontology rdf:about="http://www.opengis.net/ont/geosparql">
        ****
        <rdfs:seeAlso rdf:resource="http://www.opengis.net/def/function/ogc-geosparql/1.0"/>
        <rdfs:seeAlso rdf:resource="http://www.opengis.net/def/rule/ogc-geosparql/1.0"/>
        <rdfs:seeAlso rdf:resource="http://www.opengis.net/doc/IS/geosparql/1.0"/>
        <owl:versionInfo rdf:datatype="http://www.w3.org/2001/XMLSchema#string">OGC GeoSPARQL 1.0</owl:versionInfo>
    </owl:Ontology>

Is that right?

**Comment by lu-w** [comment]
Hi Cheng,

actually, you should not have to modify the `geosparql.rdf` file. 

I have just tested it on my machine and it was sufficient to add the following lines to the `catalog-v001.xml` in the top level folder of the A.U.T.O. repository (i.e. `auto/ontology`):

```xml
    <uri id="User Entered Import Resolution" name="http://www.opengis.net/ont/gml" uri="traffic_related/gml_32_geometries.rdf"/>
    <uri id="User Entered Import Resolution" name="http://www.opengis.net/ont/sf" uri="traffic_related/simple_features_geometries.rdf"/>
```

after downloading both files `gml_32_geometries.rdf` and `simple_features_geometries.rdf` and putting them into the `traffic_related` folder.
